# Generated by Django 5.2.4 on 2026-04-22 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_controle', '0008_alter_registrosaidaitem_patrimonio'),
        ('app_item', '0009_alter_item_quantidade_atual_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaEpiCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nome', models.CharField(max_length=60)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ano_referencia', '-mes_referencia', 'solicitante_nome'],
                'constraints': [models.UniqueConstraint(fields=('solicitante_nome', 'mes_referencia', 'ano_referencia'), name='unique_assinatura_epi_competencia')],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEpiLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentacao_saida_id_original', models.PositiveBigIntegerField()),
                ('movimentacao_saida_item_id_original', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('item_id_original', models.PositiveBigIntegerField(blank=True, null=True)),
                ('nome_item_snapshot', models.CharField(max_length=100)),
                ('grupo_item_snapshot', models.CharField(max_length=60)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateTimeField()),
                ('numero_bloco_requisicao', models.CharField(max_length=15)),
                ('setor_nome_snapshot', models.CharField(max_length=50)),
                ('responsavel_nome_snapshot', models.CharField(max_length=40)),
                ('solicitante_nome_snapshot', models.CharField(max_length=60)),
                ('patrimonio_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('foi_impresso', models.BooleanField(default=False)),
                ('impresso_em', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('cancelado_em', models.DateTimeField(blank=True, null=True)),
                ('cancelado_motivo', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='app_assinatura_epi.assinaturaepicompetencia')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_epi_lancamentos', to='app_item.item')),
                ('movimentacao_saida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_epi_lancamentos', to='app_controle.registrosaida')),
                ('movimentacao_saida_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinatura_epi_lancamento', to='app_controle.registrosaidaitem')),
            ],
            options={
                'ordering': ['-data_saida', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEpiRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante_nome', models.CharField(max_length=60)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('sequencia_relatorio', models.PositiveIntegerField()),
                ('status_assinatura', models.CharField(choices=[('pendente_assinatura', 'Pendente Assinatura'), ('assinado', 'Assinado')], default='pendente_assinatura', max_length=25)),
                ('gerado_em', models.DateTimeField(auto_now_add=True)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('assinado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_epi_relatorios_assinados', to=settings.AUTH_USER_MODEL)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='app_assinatura_epi.assinaturaepicompetencia')),
                ('gerado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assinaturas_epi_relatorios_gerados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ano_referencia', '-mes_referencia', '-sequencia_relatorio', '-gerado_em'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaEpiRelatorioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_item', to='app_assinatura_epi.assinaturaepilancamento')),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_relatorio', to='app_assinatura_epi.assinaturaepirelatorio')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='assinaturaepirelatorio',
            constraint=models.UniqueConstraint(fields=('competencia', 'sequencia_relatorio'), name='unique_assinatura_epi_relatorio_por_competencia'),
        ),
        migrations.AddConstraint(
            model_name='assinaturaepirelatorioitem',
            constraint=models.UniqueConstraint(fields=('relatorio', 'lancamento'), name='unique_assinatura_epi_relatorio_item'),
        ),
    ]
