# Generated by Django 5.2.4 on 2025-07-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True, verbose_name='Número da Nota Fiscal')),
                ('nome_fornecedor', models.CharField(max_length=100, verbose_name='Nome do Fornecedor')),
                ('cnpj_cpf', models.CharField(max_length=15, verbose_name='CNPJ ou CPF do Fornecedor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco_requisicao', models.CharField(max_length=50, verbose_name='Bloco de Requisição (Código)')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor Destino')),
                ('responsavel', models.CharField(max_length=50, verbose_name='Responsável pelo Setor')),
                ('data_saida', models.DateTimeField(auto_now_add=True, verbose_name='Data da Saída')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recebido_por', models.CharField(max_length=50, verbose_name='Recebido por')),
                ('data_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Data da Entrada')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nota_fiscal', models.ForeignKey(blank=True, help_text='Pode ser vazio se não houver nota fiscal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_controle.notafiscal', verbose_name='Nota Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Recebida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_item.item', verbose_name='Item')),
                ('registro_entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.registroentrada', verbose_name='Registro de Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSaidaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(verbose_name='Quantidade Saída')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_item.item', verbose_name='Item')),
                ('registro_saida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.registrosaida', verbose_name='Registro de Saída')),
            ],
        ),
    ]
