# Generated by Django 5.2.4 on 2025-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0002_registroentrada_alterado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosaida',
            name='bloco_requisicao',
            field=models.CharField(max_length=50, unique=True, verbose_name='Bloco de Requisição (Código)'),
        ),
    ]
