# Generated by Django 5.2.4 on 2025-08-07 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0003_alter_registrosaida_bloco_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentrada',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, help_text='Pode ser vazio se não houver nota fiscal', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_controle.notafiscal', unique=True, verbose_name='Nota Fiscal'),
        ),
    ]
