# Generated by Django 5.2.4 on 2025-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0004_alter_registroentrada_nota_fiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='cnpj_cpf',
            field=models.CharField(max_length=14, verbose_name='CNPJ ou CPF do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='numero_nota',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número da Nota Fiscal'),
        ),
        migrations.AlterField(
            model_name='registroentrada',
            name='recebido_por',
            field=models.CharField(max_length=40, verbose_name='Recebido por'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='bloco_requisicao',
            field=models.CharField(max_length=15, unique=True, verbose_name='Bloco de Requisição (Código)'),
        ),
        migrations.AlterField(
            model_name='registrosaida',
            name='responsavel',
            field=models.CharField(max_length=40, verbose_name='Responsável pelo Setor'),
        ),
    ]
