# Generated by Django 5.2.4 on 2025-08-18 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0005_alter_notafiscal_cnpj_cpf_and_more'),
        ('app_produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrosaidaitem',
            name='patrimonio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='app_produto.produto', verbose_name='Produto (Patrimônio)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrosaidaitem',
            name='solicitante',
            field=models.CharField(default=1, max_length=30, verbose_name='Solicitante do Item'),
            preserve_default=False,
        ),
    ]
