# Generated by Django 5.2.4 on 2025-09-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0006_registrosaidaitem_patrimonio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroentradaitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Recebida'),
        ),
        migrations.AlterField(
            model_name='registrosaidaitem',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Saída'),
        ),
    ]
