# Generated by Django 5.2.4 on 2026-04-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0007_alter_registroentradaitem_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosaidaitem',
            name='patrimonio',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Patrimônio'),
        ),
    ]
