# Generated by Django 5.2.4 on 2025-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo_item', models.CharField(max_length=100, verbose_name='Classe / Tipo Item')),
                ('prateleira_estoque', models.CharField(max_length=100, verbose_name='Prateleira / Estoque')),
                ('quantidade_atual', models.PositiveIntegerField(verbose_name='Quantidade Atual no Estoque')),
                ('quantidade_minima', models.PositiveIntegerField(verbose_name='Quantidade Mínima')),
                ('situacao', models.CharField(choices=[('ok', 'Estoque OK'), ('critico', 'Estoque Crítico'), ('baixo', 'Estoque Baixo'), ('esgotado', 'Esgotado')], default='ok', max_length=20, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
