# Generated by Django 5.2.4 on 2025-07-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='situacao',
            field=models.CharField(choices=[('ok', 'Estoque OK'), ('baixo', 'Estoque Baixo')], default='ok', max_length=20, verbose_name='Situação'),
        ),
    ]
