# Generated by Django 5.2.4 on 2025-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0002_alter_item_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo',
            field=models.CharField(max_length=15, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='item',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='item',
            name='prateleira_estoque',
            field=models.CharField(max_length=10, verbose_name='Prateleira / Estoque'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_item',
            field=models.CharField(max_length=40, verbose_name='Classe / Tipo Item'),
        ),
    ]
