# Generated by Django 5.2.4 on 2025-08-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0003_alter_item_codigo_alter_item_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras'),
        ),
    ]
