# Generated by Django 5.2.4 on 2025-08-11 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0004_item_codigo_barras'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40, unique=True, verbose_name='Nome do Tipo de Item')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Item',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='item',
            name='tipo_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='app_item.tipoitem', verbose_name='Classe / Tipo Item'),
        ),
    ]
