# Generated by Django 5.2.4 on 2025-08-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0005_tipoitem_alter_item_tipo_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
