# Generated by Django 5.2.4 on 2025-08-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0006_alter_item_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=20, verbose_name='Status'),
        ),
    ]
