# Generated by Django 5.2.4 on 2025-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0007_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unidade_medida',
            field=models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilo'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro'), ('cx', 'Caixa'), ('pct', 'Pacote'), ('m', 'Metro'), ('cm', 'Centímetro')], default='un', max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
