# Generated by Django 5.2.4 on 2025-09-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_item', '0008_item_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Atual no Estoque'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantidade_minima',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Mínima'),
        ),
    ]
