# Generated by Django 5.2.4 on 2025-07-20 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=25, unique=True, verbose_name='Código do Pedido')),
                ('solicitante', models.CharField(max_length=50, verbose_name='Solicitante do Pedido')),
                ('setor_destino', models.CharField(max_length=50, verbose_name='Setor Destino')),
                ('responsavel_setor', models.CharField(max_length=50, verbose_name='Responsável pelo Setor')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='enviado', max_length=20, verbose_name='Status')),
                ('motivo_recusado', models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.PositiveIntegerField(verbose_name='Quantidade Pedida')),
                ('quantidade_atual_estoque', models.PositiveIntegerField(verbose_name='Quantidade Atual no Estoque')),
                ('ultima_entrada_estoque', models.DateField(blank=True, null=True, verbose_name='Última Entrada no Estoque')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_item.item')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_pedido.pedido')),
            ],
        ),
    ]
