# Generated by Django 5.2.4 on 2025-07-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código do Pedido'),
        ),
    ]
