# Generated by Django 5.2.4 on 2025-07-24 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0002_alter_pedido_codigo_pedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
