# Generated by Django 5.2.4 on 2025-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0003_pedido_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='setor_destino',
            field=models.CharField(max_length=30, verbose_name='Setor Destino'),
        ),
    ]
