# Generated by Django 5.2.4 on 2025-09-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0004_alter_pedido_setor_destino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoitem',
            name='quantidade_pedida',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Pedida'),
        ),
    ]
