# Generated by Django 5.2.4 on 2026-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pedido', '0007_pedidoitem_adicionado_automaticamente_and_status_pendente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status_atualizado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Mudanca de Status'),
        ),
    ]
