# Generated by Django 5.2.4 on 2025-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('nivel_permissao', models.CharField(choices=[('moderador', 'Moderador'), ('administrador', 'Administrador'), ('almoxarifado', 'Almoxarifado'), ('compra', 'Compra'), ('comercial', 'Comercial')], default='comercial', max_length=30, verbose_name='Nível de Permissão')),
                ('setor', models.CharField(max_length=50, verbose_name='Setor Destino do Material')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
    ]
