# Generated by Django 5.2.4 on 2025-07-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_permissao',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('almoxarifado', 'Almoxarifado'), ('compra', 'Compra'), ('comercial', 'Comercial')], default='comercial', max_length=30, verbose_name='Nível de Permissão'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='setor',
            field=models.CharField(max_length=50, verbose_name='Setor'),
        ),
    ]
