# Generated by Django 5.2.4 on 2025-08-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0003_alter_usuario_nivel_permissao_alter_usuario_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
