# Generated by Django 5.2.4 on 2025-08-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuario', '0004_alter_usuario_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nivel_permissao',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('moderador', 'Moderador'), ('almoxarifado', 'Almoxarifado'), ('compra', 'Compra'), ('comercial', 'Comercial')], default='administrador', max_length=30, verbose_name='Nível de Permissão'),
        ),
    ]
