# Generated by Django 5.2.4 on 2025-08-18 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('tipo_plano', models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIARIO', 'Intermediário'), ('PREMIUM', 'Premium')], max_length=20)),
                ('tempo_contrato', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
