# Generated by Django 5.2.4 on 2025-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo_plano',
            field=models.CharField(choices=[('basico', 'Básico'), ('intermediario', 'Intermediário'), ('premium', 'Premium')], max_length=20),
        ),
    ]
