# Generated by Django 5.2.4 on 2025-08-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_produto', '0002_alter_produto_tipo_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='patrimonio',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
