# Generated by Django 5.2.4 on 2025-08-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_produto', '0003_alter_produto_patrimonio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_plano',
        ),
    ]
